### ISSUE TITLE
Response to issue 'Mod Suggestions? #9'

### ISSUE THREAD

**Issue by Gpeschke** [EzioTheDeadPoet/SME-FT-#12]
Thank you for looking over and including what was worth including on 'Mod Suggestions? #9' .  Had a follow up though, and it was closed. Etiquette(use if you'd like, ignore if you don't) around these things is to assign it back to me, then close it if I don't respond. Here's the followup:
-----------------------------
The reason for excluding "Missing Encounter Zones fixes" wasn't accurate- it's mod page doesn't explain itself well. The fix affects the base game, no mods needed. 

My understanding of the problem is that Encounter zones determine the level of dynamically scaling enemies . Answering the question, "Is this a hard area, or an easy one?". Them being missing means that lots of areas are marked easy that shouldn't be.

This isn't a problem, except for the exterior cell to interior cell transition. Level 6 bandits manning the walls but go through the door and all the bandits are now level 20. Both immersion breaking, and can get you killed. 

And yeah, there are mods that use the encounter zone data. Make the problem more visible. Mostly by jacking the difficulty up. So instead of a jump from level 6 to 20, it's a jump from level 10 to level 60. That's what the confusing text was about. Fix still aimed at and affects the base game.
-------------------
Here's Whiterun texture memory usage reduction:
https://www.nexusmods.com/skyrim/mods/79995
It's one of those 'no need to port for sse'
--------------------
Corrupted NIFs Patches - CNP for SE
Also not just for mods- the Oldrim mod description states that it's for the nifs from the basegame/dlcs:
"Mods, even the original files in Skyrim and its DLCs, include broken mesh files (most specifically NIF files) that could cause CTDs and some compatibility issues".

**Comment by EzioTheDeadPoet** [comment]
As far as I know you can re-open an issue as the person that created it or at least still comment on it (since iirc I didn't look the conversation). 🤔

Regarding your Mods:
- **CPN for SE** has this on the modpage:
![image](https://user-images.githubusercontent.com/52624146/104845434-c74e2e00-58d5-11eb-8ac3-92e4933a4a5a.png)
Verdict: **Will not be included.**

- **Missing Encounter Zones FIXED** makes edits that make it conflict with other mods people might add to their setup that would negate either one of the changes. So you either have the Zones fixed and those other mods are reverted or those other mods negate the fix. If there was a zEDIT or better a Synthesis patcher for this I would 100% include it, but due to the incompatibilities I won't.
Verdict: **Will not be included, unless a patcher is found/made.**

- **Whiterun texture memory usage reduction** is a mesh replacement and does need a port in form of mesh optimization.
Other than that I might include it.
verdict: **Maybe.**

**Comment by iarna** [comment]
You can't reopen if you aren't the repo owner, but you can comment on it indefinitely unless its explicitly locked. (In my experience, assigning and leaving open is definitely not general etiquette, but then, I dunno, I've pissed off a vocal minority with my ticket policies in the past. =p IMO they should serve the project maintainer, above all else, or you'll end up with a useless issue tracker.)

**Comment by EzioTheDeadPoet** [comment]
I agree and tbh I addressed all mentioned mods so I will close this Issue as well now. 😉
