### ISSUE TITLE
remove or replace alternate start with skyrim unbound

### ISSUE THREAD

**Issue by nnmrts** [EzioTheDeadPoet/SME-FT-#2]
I'm not suggesting this without a reason or just because I just think that one is better, but after years of modding this game with Alternate Start, and then switching to Unbound, I know from experience that Unbound is easier to work with.

Ingame-wise, Alternate Start is pretty intrusive and only gives you a set of scenarios to choose from, while Unbound basically almost forces you to "create" a scenario on your own. You kind of have to roleplay.

One argument against doing this is that most people probably use this list to create a modlist similar to Lexy's and that includes Alternate Start too. Also, Alternate Start is just more popular, it seems.

It's still completely up to you, if you want to replace (or even just remove  it), but just saying, for me this list would be a 10/10 instead of 9.9 if Alternate Start wasn't included. Doesn't even have to include Unbound, because that would be kinda opinionated too.

**Comment by EzioTheDeadPoet** [comment]
I will look into it maybe I will add in an alternate start category where people can choose which one they want.(sorry for the late response I somehow forgot to enable notifications.)

**Comment by EzioTheDeadPoet** [comment]
I have looked into unbound, but since it would remove the availability of the vanilla start to include it and removing ASLAL would be at a cost of stability in the sense that mods can be initialized before the highly scripted vanilla start plays and you have the ability to preset your MCM menu's I won't exclude it or change this part of the modlist but since people still have a personal preference and are allowed to use the Alternate Start they prefer have I only put it in the recommended category. I could have chosen another one but I still somehow wanted to preserve the Vanilla Skyrim Start which all the other alternate start mods would ignore.

this is why I will close this issue now I hope you can understand this and thank you for still rating it a 9.9. 
:D

**Comment by nnmrts** [comment]
Sure, no problem, I understand your decision. I actually already downloaded your modlist and am using it right now to make a "lite" lexy setup.

>  but since it would remove the availability of the vanilla start to include it

Hmmm, does it tho? Last time I checked, Unbound had that option too. Maybe I'm wrong.

**Comment by EzioTheDeadPoet** [comment]
to be completely honest I haven't loaded unbound in any of my lists and I couldn't find anything about a vanilla option on the modpage, maybe I was just to blind to find it, but my decision would still stand based on the fact that I myself simply have more experience with ASLAL than with any other AS which is why I can truly recommend it. 
But again thank you for your Input and it is great to hear that my list is being used. 👍👍😊😊
