### ISSUE TITLE
Creation Club Unofficial patches

### ISSUE THREAD

**Issue by bigrand** [EzioTheDeadPoet/SME-FT-#28]
Here is some mods that fixes and patches Club Creation content. I'm not sure why it wasn't included (I guess because not everybody uses or has Creation Club Content) but it could be included being disabled by default.

Unofficial Skyrim Creation Club Content Patches
https://www.nexusmods.com/skyrimspecialedition/mods/18975/

Unofficial Creation Club Updates - Arcane Accessories
https://www.nexusmods.com/skyrimspecialedition/mods/12748/

Unofficial Creation Club Updates - Arcane Archer Pack
https://www.nexusmods.com/skyrimspecialedition/mods/12769/

**Comment by EzioTheDeadPoet** [comment]
most people making WJ lists (which is who mostly downloads this to my knowledge) don't use any CC content for their lists as it is a bit to pricy to get everything and no one wants to just do single mods as it overcomplicates things. 

Another reason for not including them is the fact that I can't check myself what they change with the CC mods since I don't own most of them besides the few that occasionally are free.

But I will consider linking those patches in the README/website.
