### ISSUE TITLE
Add Uncapper?

### ISSUE THREAD

**Issue by kociol21** [EzioTheDeadPoet/SME-FT-#3]
Great modlist, exactly what I've been looking for. I think Uncapper is such an essential plugin that it should really be preinstalled. I mean, most people will add it anyway. And it fits the theme, utility which does nothing on itself but allows to great customization with perk/leveling overhauls of choice.

**Comment by EzioTheDeadPoet** [comment]
Will be added once I got time to do the next update and thank you for the recommendation. :D

**Comment by EzioTheDeadPoet** [comment]
I checked it out, it does alter the base game even without  an other ini tweak installed, but I will consider it as an optional Mod. Before I actually add it I am planning to ask for the general opinion about it on the Wabbajack Discord, since this list mostly tailored around the modlist creators there and they are the testing ground on what their different flavors all commonly agree on. If the concese there proves your pretty believable assumption and enough deem it essential I will definitely put it on the list. I for myself never used it in SE nor it's predecessor in LE which is another reason why I am going to make a little "survey" around this issue.

**Comment by EzioTheDeadPoet** [comment]
After asking in the wabbajack discord I have come to the desicion not to include the mod. But I really hope the list was still useful to you and maybe will in the future. 😊
