### ISSUE TITLE
Official status w/wabbajack

### ISSUE THREAD

**Issue by Gpeschke** [EzioTheDeadPoet/SME-FT-#8]
Really like this idea- had started on doing it myself when I stumbled across yours. 

Be really helpful in the near future for the lovers lab folks who are slowly making the switch to SE.
Any plans to go for official status to make this list easier to stumble upon?

**Comment by EzioTheDeadPoet** [comment]
The reason why it currently isn't official is because it is a niche list that would more fit as a resource not a full featured list. But currently there is work being done to include a new category to the UI similar to how there  currently is the NSFW category, just for resource(utility) lists, that either work like mine or have cleaned masters or some more complicated mod merges already done. Once this category Feature goes life, this list will be one of the first to go there.

**Comment by EzioTheDeadPoet** [comment]
Until this feature goes live the list can be found on the official discord as well in the #unofficial-modlists-submissions channel as the list on the top. iirc it might even have been the list that started that channels creation, but I am not 100% sure about that since it has been a while.😂

**Comment by EzioTheDeadPoet** [comment]
Official status has been reached and regarding a LL version see #11 . 

And thank you for your interest in my work. 😊
